import type { Team } from "@/types/team"

export const teams: Team[] = [
    {
        id: 1,
        name: "Natali Craig",
        email: "natali@server.com",
        memberCount: 1,
        department: "Electronics",
        status: "Active",
        dateAdded: "Feb 22, 2022",
        initials: "NC",
    },
    {
        id: 2,
        name: "Drew Cano",
        email: "drew@server.com",
        memberCount: 2,
        department: "Construction",
        status: "In-Active",
        dateAdded: "Feb 22, 2022",
        initials: "DC",
    },
    {
        id: 3,
        name: "Orlando Diggs",
        email: "orlando@server.com",
        memberCount: 3,
        department: "Labor",
        status: "On-hold",
        dateAdded: "Feb 22, 2022",
        initials: "OD",
    },
    {
        id: 4,
        name: "Andi Lane",
        email: "andi@server.com",
        memberCount: 5,
        department: "Steel Work",
        status: "Active",
        dateAdded: "Feb 22, 2022",
        initials: "AL",
    },
    {
        id: 5,
        name: "Kate Morrison",
        email: "kate@server.com",
        memberCount: 2,
        department: "Wood Work",
        status: "Active",
        dateAdded: "Feb 22, 2022",
        initials: "KM",
    },
]
