export const contractors = [
    {
        id: 1,
        name: "Natali Craig",
        email: "natali@server.com",
        phone: "(270) 555-0114",
        projectCount: 1,
        type: "Electronics",
        status: "Active",
        dateAdded: "Feb 22, 2022",
        lastActive: "Mar 14, 2022",
    },
    {
        id: 2,
        name: "Drew Cano",
        email: "drew@server.com",
        phone: "(225) 555-0118",
        projectCount: 2,
        type: "Construction",
        status: "In-Active",
        dateAdded: "Feb 22, 2022",
        lastActive: "Mar 12, 2022",
    },
    {
        id: 3,
        name: "Orlando Diggs",
        email: "orlando@server.com",
        phone: "(270) 555-0117",
        projectCount: 3,
        type: "Labor",
        status: "On-hold",
        dateAdded: "Feb 22, 2022",
        lastActive: "Mar 12, 2022",
    },
    {
        id: 4,
        name: "Andi Lane",
        email: "andi@server.com",
        phone: "(307) 555-0133",
        projectCount: 5,
        type: "Steel Work",
        status: "Active",
        dateAdded: "Feb 22, 2022",
        lastActive: "Mar 14, 2022",
    },
    {
        id: 5,
        name: "Kate Morrison",
        email: "kate@server.com",
        phone: "(671) 555-0110",
        projectCount: 2,
        type: "Wood Work",
        status: "Active",
        dateAdded: "Feb 22, 2022",
        lastActive: "Mar 13, 2022",
    },
]
