export const vendors = [
    {
        id: 1,
        name: "Natali Craig",
        email: "natali@server.com",
        productType: "Electronics",
        status: "Active",
        dateAdded: "Feb 22, 2022",
        initials: "NC",
    },
    {
        id: 2,
        name: "Drew Cano",
        email: "drew@server.com",
        productType: "Construction",
        status: "In-Active",
        dateAdded: "Feb 22, 2022",
        initials: "DC",
    },
    {
        id: 3,
        name: "Orlando Diggs",
        email: "orlando@server.com",
        productType: "Labor",
        status: "On-hold",
        dateAdded: "Feb 22, 2022",
        initials: "OD",
    },
    {
        id: 4,
        name: "Andi Lane",
        email: "andi@server.com",
        productType: "Steel Work",
        status: "Active",
        dateAdded: "Feb 22, 2022",
        initials: "AL",
    },
    {
        id: 5,
        name: "Kate Morrison",
        email: "kate@server.com",
        productType: "Wood Work",
        status: "Active",
        dateAdded: "Feb 22, 2022",
        initials: "KM",
    },
]
