/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DashboardLayoutRouteImport } from './routes/_dashboard/layout'
import { Route as RouteRouteImport } from './routes/route'
import { Route as DashboardReportsLayoutRouteImport } from './routes/_dashboard/reports/layout'
import { Route as DashboardProjectsLayoutRouteImport } from './routes/_dashboard/projects/layout'
import { Route as DashboardDocketsLayoutRouteImport } from './routes/_dashboard/dockets/layout'
import { Route as DashboardChatLayoutRouteImport } from './routes/_dashboard/chat/layout'
import { Route as DashboardReportsRouteRouteImport } from './routes/_dashboard/reports/route'
import { Route as DashboardProjectsRouteRouteImport } from './routes/_dashboard/projects/route'
import { Route as DashboardDocketsRouteRouteImport } from './routes/_dashboard/dockets/route'
import { Route as DashboardDirectoryRouteRouteImport } from './routes/_dashboard/directory/route'
import { Route as DashboardChatRouteRouteImport } from './routes/_dashboard/chat/route'
import { Route as DashboardAdminRouteRouteImport } from './routes/_dashboard/admin/route'
import { Route as AuthOtpVerificationRouteRouteImport } from './routes/_auth/otp-verification/route'
import { Route as AuthNewPasswordRouteRouteImport } from './routes/_auth/new-password/route'
import { Route as DashboardReportsIdRouteRouteImport } from './routes/_dashboard/reports/$id/route'
import { Route as DashboardProjectsIdRouteRouteImport } from './routes/_dashboard/projects/$id/route'
import { Route as DashboardDocketsIdRouteRouteImport } from './routes/_dashboard/dockets/$id/route'
import { Route as DashboardDirectoryVendorsRouteRouteImport } from './routes/_dashboard/directory/vendors/route'
import { Route as DashboardDirectoryTeamsRouteRouteImport } from './routes/_dashboard/directory/teams/route'
import { Route as DashboardDirectoryLocationsRouteRouteImport } from './routes/_dashboard/directory/locations/route'
import { Route as DashboardDirectoryEquipmentsRouteRouteImport } from './routes/_dashboard/directory/equipments/route'
import { Route as DashboardDirectoryEmployeesRouteRouteImport } from './routes/_dashboard/directory/employees/route'
import { Route as DashboardDirectoryContractorsRouteRouteImport } from './routes/_dashboard/directory/contractors/route'
import { Route as DashboardChatIdRouteRouteImport } from './routes/_dashboard/chat/$id/route'
import { Route as DashboardChatProjectIdRouteRouteImport } from './routes/_dashboard/chat/project/$id/route'

const DashboardLayoutRoute = DashboardLayoutRouteImport.update({
  id: '/_dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const RouteRoute = RouteRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardReportsLayoutRoute = DashboardReportsLayoutRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => DashboardLayoutRoute,
} as any)
const DashboardProjectsLayoutRoute = DashboardProjectsLayoutRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => DashboardLayoutRoute,
} as any)
const DashboardDocketsLayoutRoute = DashboardDocketsLayoutRouteImport.update({
  id: '/dockets',
  path: '/dockets',
  getParentRoute: () => DashboardLayoutRoute,
} as any)
const DashboardChatLayoutRoute = DashboardChatLayoutRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => DashboardLayoutRoute,
} as any)
const DashboardReportsRouteRoute = DashboardReportsRouteRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardReportsLayoutRoute,
} as any)
const DashboardProjectsRouteRoute = DashboardProjectsRouteRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardProjectsLayoutRoute,
} as any)
const DashboardDocketsRouteRoute = DashboardDocketsRouteRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardDocketsLayoutRoute,
} as any)
const DashboardDirectoryRouteRoute = DashboardDirectoryRouteRouteImport.update({
  id: '/directory/',
  path: '/directory/',
  getParentRoute: () => DashboardLayoutRoute,
} as any)
const DashboardChatRouteRoute = DashboardChatRouteRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardChatLayoutRoute,
} as any)
const DashboardAdminRouteRoute = DashboardAdminRouteRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => DashboardLayoutRoute,
} as any)
const AuthOtpVerificationRouteRoute =
  AuthOtpVerificationRouteRouteImport.update({
    id: '/_auth/otp-verification/',
    path: '/otp-verification/',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthNewPasswordRouteRoute = AuthNewPasswordRouteRouteImport.update({
  id: '/_auth/new-password/',
  path: '/new-password/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardReportsIdRouteRoute = DashboardReportsIdRouteRouteImport.update({
  id: '/$id/',
  path: '/$id/',
  getParentRoute: () => DashboardReportsLayoutRoute,
} as any)
const DashboardProjectsIdRouteRoute =
  DashboardProjectsIdRouteRouteImport.update({
    id: '/$id/',
    path: '/$id/',
    getParentRoute: () => DashboardProjectsLayoutRoute,
  } as any)
const DashboardDocketsIdRouteRoute = DashboardDocketsIdRouteRouteImport.update({
  id: '/$id/',
  path: '/$id/',
  getParentRoute: () => DashboardDocketsLayoutRoute,
} as any)
const DashboardDirectoryVendorsRouteRoute =
  DashboardDirectoryVendorsRouteRouteImport.update({
    id: '/directory/vendors/',
    path: '/directory/vendors/',
    getParentRoute: () => DashboardLayoutRoute,
  } as any)
const DashboardDirectoryTeamsRouteRoute =
  DashboardDirectoryTeamsRouteRouteImport.update({
    id: '/directory/teams/',
    path: '/directory/teams/',
    getParentRoute: () => DashboardLayoutRoute,
  } as any)
const DashboardDirectoryLocationsRouteRoute =
  DashboardDirectoryLocationsRouteRouteImport.update({
    id: '/directory/locations/',
    path: '/directory/locations/',
    getParentRoute: () => DashboardLayoutRoute,
  } as any)
const DashboardDirectoryEquipmentsRouteRoute =
  DashboardDirectoryEquipmentsRouteRouteImport.update({
    id: '/directory/equipments/',
    path: '/directory/equipments/',
    getParentRoute: () => DashboardLayoutRoute,
  } as any)
const DashboardDirectoryEmployeesRouteRoute =
  DashboardDirectoryEmployeesRouteRouteImport.update({
    id: '/directory/employees/',
    path: '/directory/employees/',
    getParentRoute: () => DashboardLayoutRoute,
  } as any)
const DashboardDirectoryContractorsRouteRoute =
  DashboardDirectoryContractorsRouteRouteImport.update({
    id: '/directory/contractors/',
    path: '/directory/contractors/',
    getParentRoute: () => DashboardLayoutRoute,
  } as any)
const DashboardChatIdRouteRoute = DashboardChatIdRouteRouteImport.update({
  id: '/$id/',
  path: '/$id/',
  getParentRoute: () => DashboardChatLayoutRoute,
} as any)
const DashboardChatProjectIdRouteRoute =
  DashboardChatProjectIdRouteRouteImport.update({
    id: '/project/$id/',
    path: '/project/$id/',
    getParentRoute: () => DashboardChatLayoutRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof RouteRoute
  '/chat': typeof DashboardChatLayoutRouteWithChildren
  '/dockets': typeof DashboardDocketsLayoutRouteWithChildren
  '/projects': typeof DashboardProjectsLayoutRouteWithChildren
  '/reports': typeof DashboardReportsLayoutRouteWithChildren
  '/new-password': typeof AuthNewPasswordRouteRoute
  '/otp-verification': typeof AuthOtpVerificationRouteRoute
  '/admin': typeof DashboardAdminRouteRoute
  '/chat/': typeof DashboardChatRouteRoute
  '/directory': typeof DashboardDirectoryRouteRoute
  '/dockets/': typeof DashboardDocketsRouteRoute
  '/projects/': typeof DashboardProjectsRouteRoute
  '/reports/': typeof DashboardReportsRouteRoute
  '/chat/$id': typeof DashboardChatIdRouteRoute
  '/directory/contractors': typeof DashboardDirectoryContractorsRouteRoute
  '/directory/employees': typeof DashboardDirectoryEmployeesRouteRoute
  '/directory/equipments': typeof DashboardDirectoryEquipmentsRouteRoute
  '/directory/locations': typeof DashboardDirectoryLocationsRouteRoute
  '/directory/teams': typeof DashboardDirectoryTeamsRouteRoute
  '/directory/vendors': typeof DashboardDirectoryVendorsRouteRoute
  '/dockets/$id': typeof DashboardDocketsIdRouteRoute
  '/projects/$id': typeof DashboardProjectsIdRouteRoute
  '/reports/$id': typeof DashboardReportsIdRouteRoute
  '/chat/project/$id': typeof DashboardChatProjectIdRouteRoute
}
export interface FileRoutesByTo {
  '/': typeof RouteRoute
  '/new-password': typeof AuthNewPasswordRouteRoute
  '/otp-verification': typeof AuthOtpVerificationRouteRoute
  '/admin': typeof DashboardAdminRouteRoute
  '/chat': typeof DashboardChatRouteRoute
  '/directory': typeof DashboardDirectoryRouteRoute
  '/dockets': typeof DashboardDocketsRouteRoute
  '/projects': typeof DashboardProjectsRouteRoute
  '/reports': typeof DashboardReportsRouteRoute
  '/chat/$id': typeof DashboardChatIdRouteRoute
  '/directory/contractors': typeof DashboardDirectoryContractorsRouteRoute
  '/directory/employees': typeof DashboardDirectoryEmployeesRouteRoute
  '/directory/equipments': typeof DashboardDirectoryEquipmentsRouteRoute
  '/directory/locations': typeof DashboardDirectoryLocationsRouteRoute
  '/directory/teams': typeof DashboardDirectoryTeamsRouteRoute
  '/directory/vendors': typeof DashboardDirectoryVendorsRouteRoute
  '/dockets/$id': typeof DashboardDocketsIdRouteRoute
  '/projects/$id': typeof DashboardProjectsIdRouteRoute
  '/reports/$id': typeof DashboardReportsIdRouteRoute
  '/chat/project/$id': typeof DashboardChatProjectIdRouteRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof RouteRoute
  '/_dashboard': typeof DashboardLayoutRouteWithChildren
  '/_dashboard/chat': typeof DashboardChatLayoutRouteWithChildren
  '/_dashboard/dockets': typeof DashboardDocketsLayoutRouteWithChildren
  '/_dashboard/projects': typeof DashboardProjectsLayoutRouteWithChildren
  '/_dashboard/reports': typeof DashboardReportsLayoutRouteWithChildren
  '/_auth/new-password/': typeof AuthNewPasswordRouteRoute
  '/_auth/otp-verification/': typeof AuthOtpVerificationRouteRoute
  '/_dashboard/admin/': typeof DashboardAdminRouteRoute
  '/_dashboard/chat/': typeof DashboardChatRouteRoute
  '/_dashboard/directory/': typeof DashboardDirectoryRouteRoute
  '/_dashboard/dockets/': typeof DashboardDocketsRouteRoute
  '/_dashboard/projects/': typeof DashboardProjectsRouteRoute
  '/_dashboard/reports/': typeof DashboardReportsRouteRoute
  '/_dashboard/chat/$id/': typeof DashboardChatIdRouteRoute
  '/_dashboard/directory/contractors/': typeof DashboardDirectoryContractorsRouteRoute
  '/_dashboard/directory/employees/': typeof DashboardDirectoryEmployeesRouteRoute
  '/_dashboard/directory/equipments/': typeof DashboardDirectoryEquipmentsRouteRoute
  '/_dashboard/directory/locations/': typeof DashboardDirectoryLocationsRouteRoute
  '/_dashboard/directory/teams/': typeof DashboardDirectoryTeamsRouteRoute
  '/_dashboard/directory/vendors/': typeof DashboardDirectoryVendorsRouteRoute
  '/_dashboard/dockets/$id/': typeof DashboardDocketsIdRouteRoute
  '/_dashboard/projects/$id/': typeof DashboardProjectsIdRouteRoute
  '/_dashboard/reports/$id/': typeof DashboardReportsIdRouteRoute
  '/_dashboard/chat/project/$id/': typeof DashboardChatProjectIdRouteRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/chat'
    | '/dockets'
    | '/projects'
    | '/reports'
    | '/new-password'
    | '/otp-verification'
    | '/admin'
    | '/chat/'
    | '/directory'
    | '/dockets/'
    | '/projects/'
    | '/reports/'
    | '/chat/$id'
    | '/directory/contractors'
    | '/directory/employees'
    | '/directory/equipments'
    | '/directory/locations'
    | '/directory/teams'
    | '/directory/vendors'
    | '/dockets/$id'
    | '/projects/$id'
    | '/reports/$id'
    | '/chat/project/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/new-password'
    | '/otp-verification'
    | '/admin'
    | '/chat'
    | '/directory'
    | '/dockets'
    | '/projects'
    | '/reports'
    | '/chat/$id'
    | '/directory/contractors'
    | '/directory/employees'
    | '/directory/equipments'
    | '/directory/locations'
    | '/directory/teams'
    | '/directory/vendors'
    | '/dockets/$id'
    | '/projects/$id'
    | '/reports/$id'
    | '/chat/project/$id'
  id:
    | '__root__'
    | '/'
    | '/_dashboard'
    | '/_dashboard/chat'
    | '/_dashboard/dockets'
    | '/_dashboard/projects'
    | '/_dashboard/reports'
    | '/_auth/new-password/'
    | '/_auth/otp-verification/'
    | '/_dashboard/admin/'
    | '/_dashboard/chat/'
    | '/_dashboard/directory/'
    | '/_dashboard/dockets/'
    | '/_dashboard/projects/'
    | '/_dashboard/reports/'
    | '/_dashboard/chat/$id/'
    | '/_dashboard/directory/contractors/'
    | '/_dashboard/directory/employees/'
    | '/_dashboard/directory/equipments/'
    | '/_dashboard/directory/locations/'
    | '/_dashboard/directory/teams/'
    | '/_dashboard/directory/vendors/'
    | '/_dashboard/dockets/$id/'
    | '/_dashboard/projects/$id/'
    | '/_dashboard/reports/$id/'
    | '/_dashboard/chat/project/$id/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  RouteRoute: typeof RouteRoute
  DashboardLayoutRoute: typeof DashboardLayoutRouteWithChildren
  AuthNewPasswordRouteRoute: typeof AuthNewPasswordRouteRoute
  AuthOtpVerificationRouteRoute: typeof AuthOtpVerificationRouteRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_dashboard': {
      id: '/_dashboard'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof DashboardLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof RouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_dashboard/reports': {
      id: '/_dashboard/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof DashboardReportsLayoutRouteImport
      parentRoute: typeof DashboardLayoutRoute
    }
    '/_dashboard/projects': {
      id: '/_dashboard/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof DashboardProjectsLayoutRouteImport
      parentRoute: typeof DashboardLayoutRoute
    }
    '/_dashboard/dockets': {
      id: '/_dashboard/dockets'
      path: '/dockets'
      fullPath: '/dockets'
      preLoaderRoute: typeof DashboardDocketsLayoutRouteImport
      parentRoute: typeof DashboardLayoutRoute
    }
    '/_dashboard/chat': {
      id: '/_dashboard/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof DashboardChatLayoutRouteImport
      parentRoute: typeof DashboardLayoutRoute
    }
    '/_dashboard/reports/': {
      id: '/_dashboard/reports/'
      path: '/'
      fullPath: '/reports/'
      preLoaderRoute: typeof DashboardReportsRouteRouteImport
      parentRoute: typeof DashboardReportsLayoutRoute
    }
    '/_dashboard/projects/': {
      id: '/_dashboard/projects/'
      path: '/'
      fullPath: '/projects/'
      preLoaderRoute: typeof DashboardProjectsRouteRouteImport
      parentRoute: typeof DashboardProjectsLayoutRoute
    }
    '/_dashboard/dockets/': {
      id: '/_dashboard/dockets/'
      path: '/'
      fullPath: '/dockets/'
      preLoaderRoute: typeof DashboardDocketsRouteRouteImport
      parentRoute: typeof DashboardDocketsLayoutRoute
    }
    '/_dashboard/directory/': {
      id: '/_dashboard/directory/'
      path: '/directory'
      fullPath: '/directory'
      preLoaderRoute: typeof DashboardDirectoryRouteRouteImport
      parentRoute: typeof DashboardLayoutRoute
    }
    '/_dashboard/chat/': {
      id: '/_dashboard/chat/'
      path: '/'
      fullPath: '/chat/'
      preLoaderRoute: typeof DashboardChatRouteRouteImport
      parentRoute: typeof DashboardChatLayoutRoute
    }
    '/_dashboard/admin/': {
      id: '/_dashboard/admin/'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof DashboardAdminRouteRouteImport
      parentRoute: typeof DashboardLayoutRoute
    }
    '/_auth/otp-verification/': {
      id: '/_auth/otp-verification/'
      path: '/otp-verification'
      fullPath: '/otp-verification'
      preLoaderRoute: typeof AuthOtpVerificationRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/new-password/': {
      id: '/_auth/new-password/'
      path: '/new-password'
      fullPath: '/new-password'
      preLoaderRoute: typeof AuthNewPasswordRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_dashboard/reports/$id/': {
      id: '/_dashboard/reports/$id/'
      path: '/$id'
      fullPath: '/reports/$id'
      preLoaderRoute: typeof DashboardReportsIdRouteRouteImport
      parentRoute: typeof DashboardReportsLayoutRoute
    }
    '/_dashboard/projects/$id/': {
      id: '/_dashboard/projects/$id/'
      path: '/$id'
      fullPath: '/projects/$id'
      preLoaderRoute: typeof DashboardProjectsIdRouteRouteImport
      parentRoute: typeof DashboardProjectsLayoutRoute
    }
    '/_dashboard/dockets/$id/': {
      id: '/_dashboard/dockets/$id/'
      path: '/$id'
      fullPath: '/dockets/$id'
      preLoaderRoute: typeof DashboardDocketsIdRouteRouteImport
      parentRoute: typeof DashboardDocketsLayoutRoute
    }
    '/_dashboard/directory/vendors/': {
      id: '/_dashboard/directory/vendors/'
      path: '/directory/vendors'
      fullPath: '/directory/vendors'
      preLoaderRoute: typeof DashboardDirectoryVendorsRouteRouteImport
      parentRoute: typeof DashboardLayoutRoute
    }
    '/_dashboard/directory/teams/': {
      id: '/_dashboard/directory/teams/'
      path: '/directory/teams'
      fullPath: '/directory/teams'
      preLoaderRoute: typeof DashboardDirectoryTeamsRouteRouteImport
      parentRoute: typeof DashboardLayoutRoute
    }
    '/_dashboard/directory/locations/': {
      id: '/_dashboard/directory/locations/'
      path: '/directory/locations'
      fullPath: '/directory/locations'
      preLoaderRoute: typeof DashboardDirectoryLocationsRouteRouteImport
      parentRoute: typeof DashboardLayoutRoute
    }
    '/_dashboard/directory/equipments/': {
      id: '/_dashboard/directory/equipments/'
      path: '/directory/equipments'
      fullPath: '/directory/equipments'
      preLoaderRoute: typeof DashboardDirectoryEquipmentsRouteRouteImport
      parentRoute: typeof DashboardLayoutRoute
    }
    '/_dashboard/directory/employees/': {
      id: '/_dashboard/directory/employees/'
      path: '/directory/employees'
      fullPath: '/directory/employees'
      preLoaderRoute: typeof DashboardDirectoryEmployeesRouteRouteImport
      parentRoute: typeof DashboardLayoutRoute
    }
    '/_dashboard/directory/contractors/': {
      id: '/_dashboard/directory/contractors/'
      path: '/directory/contractors'
      fullPath: '/directory/contractors'
      preLoaderRoute: typeof DashboardDirectoryContractorsRouteRouteImport
      parentRoute: typeof DashboardLayoutRoute
    }
    '/_dashboard/chat/$id/': {
      id: '/_dashboard/chat/$id/'
      path: '/$id'
      fullPath: '/chat/$id'
      preLoaderRoute: typeof DashboardChatIdRouteRouteImport
      parentRoute: typeof DashboardChatLayoutRoute
    }
    '/_dashboard/chat/project/$id/': {
      id: '/_dashboard/chat/project/$id/'
      path: '/project/$id'
      fullPath: '/chat/project/$id'
      preLoaderRoute: typeof DashboardChatProjectIdRouteRouteImport
      parentRoute: typeof DashboardChatLayoutRoute
    }
  }
}

interface DashboardChatLayoutRouteChildren {
  DashboardChatRouteRoute: typeof DashboardChatRouteRoute
  DashboardChatIdRouteRoute: typeof DashboardChatIdRouteRoute
  DashboardChatProjectIdRouteRoute: typeof DashboardChatProjectIdRouteRoute
}

const DashboardChatLayoutRouteChildren: DashboardChatLayoutRouteChildren = {
  DashboardChatRouteRoute: DashboardChatRouteRoute,
  DashboardChatIdRouteRoute: DashboardChatIdRouteRoute,
  DashboardChatProjectIdRouteRoute: DashboardChatProjectIdRouteRoute,
}

const DashboardChatLayoutRouteWithChildren =
  DashboardChatLayoutRoute._addFileChildren(DashboardChatLayoutRouteChildren)

interface DashboardDocketsLayoutRouteChildren {
  DashboardDocketsRouteRoute: typeof DashboardDocketsRouteRoute
  DashboardDocketsIdRouteRoute: typeof DashboardDocketsIdRouteRoute
}

const DashboardDocketsLayoutRouteChildren: DashboardDocketsLayoutRouteChildren =
  {
    DashboardDocketsRouteRoute: DashboardDocketsRouteRoute,
    DashboardDocketsIdRouteRoute: DashboardDocketsIdRouteRoute,
  }

const DashboardDocketsLayoutRouteWithChildren =
  DashboardDocketsLayoutRoute._addFileChildren(
    DashboardDocketsLayoutRouteChildren,
  )

interface DashboardProjectsLayoutRouteChildren {
  DashboardProjectsRouteRoute: typeof DashboardProjectsRouteRoute
  DashboardProjectsIdRouteRoute: typeof DashboardProjectsIdRouteRoute
}

const DashboardProjectsLayoutRouteChildren: DashboardProjectsLayoutRouteChildren =
  {
    DashboardProjectsRouteRoute: DashboardProjectsRouteRoute,
    DashboardProjectsIdRouteRoute: DashboardProjectsIdRouteRoute,
  }

const DashboardProjectsLayoutRouteWithChildren =
  DashboardProjectsLayoutRoute._addFileChildren(
    DashboardProjectsLayoutRouteChildren,
  )

interface DashboardReportsLayoutRouteChildren {
  DashboardReportsRouteRoute: typeof DashboardReportsRouteRoute
  DashboardReportsIdRouteRoute: typeof DashboardReportsIdRouteRoute
}

const DashboardReportsLayoutRouteChildren: DashboardReportsLayoutRouteChildren =
  {
    DashboardReportsRouteRoute: DashboardReportsRouteRoute,
    DashboardReportsIdRouteRoute: DashboardReportsIdRouteRoute,
  }

const DashboardReportsLayoutRouteWithChildren =
  DashboardReportsLayoutRoute._addFileChildren(
    DashboardReportsLayoutRouteChildren,
  )

interface DashboardLayoutRouteChildren {
  DashboardChatLayoutRoute: typeof DashboardChatLayoutRouteWithChildren
  DashboardDocketsLayoutRoute: typeof DashboardDocketsLayoutRouteWithChildren
  DashboardProjectsLayoutRoute: typeof DashboardProjectsLayoutRouteWithChildren
  DashboardReportsLayoutRoute: typeof DashboardReportsLayoutRouteWithChildren
  DashboardAdminRouteRoute: typeof DashboardAdminRouteRoute
  DashboardDirectoryRouteRoute: typeof DashboardDirectoryRouteRoute
  DashboardDirectoryContractorsRouteRoute: typeof DashboardDirectoryContractorsRouteRoute
  DashboardDirectoryEmployeesRouteRoute: typeof DashboardDirectoryEmployeesRouteRoute
  DashboardDirectoryEquipmentsRouteRoute: typeof DashboardDirectoryEquipmentsRouteRoute
  DashboardDirectoryLocationsRouteRoute: typeof DashboardDirectoryLocationsRouteRoute
  DashboardDirectoryTeamsRouteRoute: typeof DashboardDirectoryTeamsRouteRoute
  DashboardDirectoryVendorsRouteRoute: typeof DashboardDirectoryVendorsRouteRoute
}

const DashboardLayoutRouteChildren: DashboardLayoutRouteChildren = {
  DashboardChatLayoutRoute: DashboardChatLayoutRouteWithChildren,
  DashboardDocketsLayoutRoute: DashboardDocketsLayoutRouteWithChildren,
  DashboardProjectsLayoutRoute: DashboardProjectsLayoutRouteWithChildren,
  DashboardReportsLayoutRoute: DashboardReportsLayoutRouteWithChildren,
  DashboardAdminRouteRoute: DashboardAdminRouteRoute,
  DashboardDirectoryRouteRoute: DashboardDirectoryRouteRoute,
  DashboardDirectoryContractorsRouteRoute:
    DashboardDirectoryContractorsRouteRoute,
  DashboardDirectoryEmployeesRouteRoute: DashboardDirectoryEmployeesRouteRoute,
  DashboardDirectoryEquipmentsRouteRoute:
    DashboardDirectoryEquipmentsRouteRoute,
  DashboardDirectoryLocationsRouteRoute: DashboardDirectoryLocationsRouteRoute,
  DashboardDirectoryTeamsRouteRoute: DashboardDirectoryTeamsRouteRoute,
  DashboardDirectoryVendorsRouteRoute: DashboardDirectoryVendorsRouteRoute,
}

const DashboardLayoutRouteWithChildren = DashboardLayoutRoute._addFileChildren(
  DashboardLayoutRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  RouteRoute: RouteRoute,
  DashboardLayoutRoute: DashboardLayoutRouteWithChildren,
  AuthNewPasswordRouteRoute: AuthNewPasswordRouteRoute,
  AuthOtpVerificationRouteRoute: AuthOtpVerificationRouteRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
